
sudo: required

services:
  - docker

before_install:
  - docker build -t aman8859/contact-app -f ./server/Dockerfile ./server
  
script:
  - docker run -e CI=true aman8859/contact-app npm run test

after_success:
  - docker build -t aman8859/multi-client ./client
  - docker build -t aman8859/multi-nginx ./nginx
  - docker build -t aman8859/multi-server ./server  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aman8859/multi-client
  - docker push aman8859/multi-nginx
  - docker push aman8859/multi-server

